feat: target Minecraft 1.21.2, add publishing
Now targets 1.21.2 on fabric!

We now publish separate JARs for each project, and publish to william278.net

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,27 +1,246 @@
-# Builds, tests the project with Gradle and uploads to Modrinth
-name: Java CI
+name: CI Tests
 
 on:
   push:
     branches: [ 'master' ]
+    paths-ignore:
+      - 'workflows/**'
+      - 'README.md'
 
 permissions:
   contents: read
+  checks: write
 
 jobs:
   build:
+    name: 'Build'
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up JDK 21
-        uses: actions/setup-java@v3
+      - name: 'Setup JDK 21 📦'
+        uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
-      - name: Build with Gradle
-        uses: gradle/gradle-build-action@v2
+      - name: 'Setup Gradle 8.10 🏗️'
+        uses: gradle/actions/setup-gradle@v4
         with:
-          arguments: build test publish
+          gradle-version: '8.10'
+      - name: 'Checkout for CI 🛎️'
+        uses: actions/checkout@v4
         env:
           SNAPSHOTS_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
           SNAPSHOTS_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
+      - name: 'Build 🛎️'
+        run: |
+          ./gradlew clean build publish
+      - name: 'Publish Test Report 📊'
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # Continue on failure
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+      - name: 'Fetch Version String 📝'
+        run: |
+          echo "::set-output name=VERSION_NAME::$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
+        id: fetch-version
+      - name: 'Set Version Variable 📝'
+        run: |
+          echo "version_name=${{steps.fetch-version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
+      - name: 'Publish to William278.net 🚀'
+        uses: WiIIiam278/bones-publish-action@v1
+        with:
+          api-key: ${{ secrets.BONES_API_KEY }}
+          project: 'papiproxybridge'
+          channel: 'alpha'
+          version: ${{ env.version_name }}
+          changelog: ${{ github.event.head_commit.message }}
+          distro-names: |
+            paper
+            fabric-1.21.2
+            velocity
+            bungeecord
+          distro-groups: |
+            paper
+            fabric
+            velocity
+            bungeecord
+          distro-descriptions: |
+            Paper
+            Fabric 1.21.1
+            Velocity
+            BungeeCord
+          files: |
+            target/PAPIProxyBridge-Bukkit-${{ env.version_name }}.jar
+            target/PAPIProxyBridge-Fabric-${{ env.version_name }}+mc.1.21.2.jar
+            target/PAPIProxyBridge-Velocity-${{ env.version_name }}.jar
+            target/PAPIProxyBridge-Bungee-${{ env.version_name }}.jar
+      - name: 'Spigot: Publish to Modrinth'
+        uses: WiIIiam278/mc-publish@hangar
+        if: success() || failure()
+        with:
+          modrinth-id: bEIUEGTX
+          modrinth-featured: false
+          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          modrinth-dependencies: |
+            placeholderapi | suggests | *
+          files-primary: target/PAPIProxyBridge-Bukkit-${{ env.version_name }}.jar
+          name: PAPIProxyBridge (Spigot) v${{ env.version_name }}
+          version: ${{ env.version_name }}
+          version-type: alpha
+          changelog: ${{ github.event.head_commit.message }}
+          loaders: |
+            spigot
+            paper
+            folia
+          game-versions: |
+            1.17.1
+            1.18
+            1.18.1
+            1.18.2
+            1.19
+            1.19.1
+            1.19.2
+            1.19.3
+            1.19.4
+            1.20
+            1.20.1
+            1.20.2
+            1.20.3
+            1.20.4
+            1.20.5
+            1.20.6
+            1.21
+            1.21.1
+            1.21.2
+          java: 17
+      - name: 'Fabric: Publish to Modrinth'
+        uses: WiIIiam278/mc-publish@hangar
+        if: success() || failure()
+        with:
+          modrinth-id: bEIUEGTX
+          modrinth-featured: false
+          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          modrinth-dependencies: |
+            placeholderapi | suggests | *
+          files-primary: target/PAPIProxyBridge-Fabric-${{ env.version_name }}+mc.1.21.2.jar
+          name: PAPIProxyBridge (Fabric) v${{ env.version_name }}
+          version: ${{ env.version_name }}
+          version-type: alpha
+          changelog: ${{ github.event.head_commit.message }}
+          loaders: |
+            fabric
+          game-versions: |
+            1.21.2
+          java: 17
+      - name: 'Bungee: Publish to Modrinth'
+        uses: WiIIiam278/mc-publish@hangar
+        if: success() || failure()
+        with:
+          modrinth-id: bEIUEGTX
+          modrinth-featured: false
+          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          files-primary: target/PAPIProxyBridge-Bungee-${{ env.version_name }}.jar
+          name: PAPIProxyBridge (Bungee) v${{ env.version_name }}
+          version: ${{ env.version_name }}
+          version-type: alpha
+          changelog: ${{ github.event.head_commit.message }}
+          loaders: |
+            bungeecord
+            waterfall
+          game-versions: |
+            1.17.1
+            1.18
+            1.18.1
+            1.18.2
+            1.19
+            1.19.1
+            1.19.2
+            1.19.3
+            1.19.4
+            1.20
+            1.20.1
+            1.20.2
+            1.20.3
+            1.20.4
+            1.20.5
+            1.20.6
+            1.21
+            1.21.1
+            1.21.2
+          java: 21
+      - name: 'Velocity: Publish to Modrinth'
+        uses: WiIIiam278/mc-publish@hangar
+        if: success() || failure()
+        with:
+          modrinth-id: bEIUEGTX
+          modrinth-featured: false
+          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+          modrinth-dependencies: |
+            placeholderapi | suggests | *
+          files-primary: target/PAPIProxyBridge-Velocity-${{ env.version_name }}.jar
+          name: PAPIProxyBridge (Velocity) v${{ env.version_name }}
+          version: ${{ env.version_name }}
+          version-type: alpha
+          changelog: ${{ github.event.head_commit.message }}
+          loaders: |
+            velocity
+          game-versions: |
+            1.17.1
+            1.18
+            1.18.1
+            1.18.2
+            1.19
+            1.19.1
+            1.19.2
+            1.19.3
+            1.19.4
+            1.20
+            1.20.1
+            1.20.2
+            1.20.3
+            1.20.4
+            1.20.5
+            1.20.6
+            1.21
+            1.21.1
+            1.21.2
+          java: 17
+      - name: 'All: Publish to Hangar'
+        uses: WiIIiam278/mc-publish@hangar
+        if: success() || failure()
+        with:
+          hangar-id: William278/PAPIProxyBridge
+          hangar-token: ${{ secrets.HANGAR_API_KEY }}
+          hangar-version-type: Alpha
+          files-primary: |
+            target/PAPIProxyBridge-Velocity-${{ env.version_name }}.jar
+            target/PAPIProxyBridge-Bungee-${{ env.version_name }}.jar
+            target/PAPIProxyBridge-Bukkit-${{ env.version_name }}.jar
+          name: PAPIProxyBridge (Velocity) v${{ env.version_name }}
+          version: ${{ env.version_name }}
+          version-type: alpha
+          changelog: ${{ github.event.head_commit.message }}
+          loaders: |
+            velocity
+            waterfall
+            paper
+          game-versions: |
+            1.17.1
+            1.18
+            1.18.1
+            1.18.2
+            1.19
+            1.19.1
+            1.19.2
+            1.19.3
+            1.19.4
+            1.20
+            1.20.1
+            1.20.2
+            1.20.3
+            1.20.4
+            1.20.5
+            1.20.6
+            1.21
+            1.21.1
+            1.21.2
+          java: 17
